//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.19 at 01:24:49 AM CEST 
//


package org.zmeu.blog.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for BlacklistStatusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BlacklistStatusType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="is_address_blacklist" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="period_address_blacklist" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="is_email_blacklist" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="period_email_blacklist" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="is_fraud_blacklist" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="period_fraud_blacklist" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="is_identity_blacklist" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="period_identity_blacklist" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="is_global_whitelist" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="period_global_whitelist" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="is_merchant_whitelist" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="period_merchant_whitelist" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="is_ip_frequency_limit_reached" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="is_invalid_email" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BlacklistStatusType", propOrder = {
    "isAddressBlacklist",
    "periodAddressBlacklist",
    "isEmailBlacklist",
    "periodEmailBlacklist",
    "isFraudBlacklist",
    "periodFraudBlacklist",
    "isIdentityBlacklist",
    "periodIdentityBlacklist",
    "isGlobalWhitelist",
    "periodGlobalWhitelist",
    "isMerchantWhitelist",
    "periodMerchantWhitelist",
    "isIpFrequencyLimitReached",
    "isInvalidEmail"
})
public class BlacklistStatusType
    implements ToString
{

    @XmlElement(name = "is_address_blacklist")
    protected boolean isAddressBlacklist;
    @XmlElement(name = "period_address_blacklist")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar periodAddressBlacklist;
    @XmlElement(name = "is_email_blacklist")
    protected boolean isEmailBlacklist;
    @XmlElement(name = "period_email_blacklist")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar periodEmailBlacklist;
    @XmlElement(name = "is_fraud_blacklist")
    protected boolean isFraudBlacklist;
    @XmlElement(name = "period_fraud_blacklist")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar periodFraudBlacklist;
    @XmlElement(name = "is_identity_blacklist")
    protected boolean isIdentityBlacklist;
    @XmlElement(name = "period_identity_blacklist")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar periodIdentityBlacklist;
    @XmlElement(name = "is_global_whitelist")
    protected boolean isGlobalWhitelist;
    @XmlElement(name = "period_global_whitelist")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar periodGlobalWhitelist;
    @XmlElement(name = "is_merchant_whitelist")
    protected boolean isMerchantWhitelist;
    @XmlElement(name = "period_merchant_whitelist")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar periodMerchantWhitelist;
    @XmlElement(name = "is_ip_frequency_limit_reached")
    protected boolean isIpFrequencyLimitReached;
    @XmlElement(name = "is_invalid_email")
    protected boolean isInvalidEmail;

    /**
     * Gets the value of the isAddressBlacklist property.
     * 
     */
    public boolean isIsAddressBlacklist() {
        return isAddressBlacklist;
    }

    /**
     * Sets the value of the isAddressBlacklist property.
     * 
     */
    public void setIsAddressBlacklist(boolean value) {
        this.isAddressBlacklist = value;
    }

    /**
     * Gets the value of the periodAddressBlacklist property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPeriodAddressBlacklist() {
        return periodAddressBlacklist;
    }

    /**
     * Sets the value of the periodAddressBlacklist property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPeriodAddressBlacklist(XMLGregorianCalendar value) {
        this.periodAddressBlacklist = value;
    }

    /**
     * Gets the value of the isEmailBlacklist property.
     * 
     */
    public boolean isIsEmailBlacklist() {
        return isEmailBlacklist;
    }

    /**
     * Sets the value of the isEmailBlacklist property.
     * 
     */
    public void setIsEmailBlacklist(boolean value) {
        this.isEmailBlacklist = value;
    }

    /**
     * Gets the value of the periodEmailBlacklist property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPeriodEmailBlacklist() {
        return periodEmailBlacklist;
    }

    /**
     * Sets the value of the periodEmailBlacklist property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPeriodEmailBlacklist(XMLGregorianCalendar value) {
        this.periodEmailBlacklist = value;
    }

    /**
     * Gets the value of the isFraudBlacklist property.
     * 
     */
    public boolean isIsFraudBlacklist() {
        return isFraudBlacklist;
    }

    /**
     * Sets the value of the isFraudBlacklist property.
     * 
     */
    public void setIsFraudBlacklist(boolean value) {
        this.isFraudBlacklist = value;
    }

    /**
     * Gets the value of the periodFraudBlacklist property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPeriodFraudBlacklist() {
        return periodFraudBlacklist;
    }

    /**
     * Sets the value of the periodFraudBlacklist property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPeriodFraudBlacklist(XMLGregorianCalendar value) {
        this.periodFraudBlacklist = value;
    }

    /**
     * Gets the value of the isIdentityBlacklist property.
     * 
     */
    public boolean isIsIdentityBlacklist() {
        return isIdentityBlacklist;
    }

    /**
     * Sets the value of the isIdentityBlacklist property.
     * 
     */
    public void setIsIdentityBlacklist(boolean value) {
        this.isIdentityBlacklist = value;
    }

    /**
     * Gets the value of the periodIdentityBlacklist property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPeriodIdentityBlacklist() {
        return periodIdentityBlacklist;
    }

    /**
     * Sets the value of the periodIdentityBlacklist property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPeriodIdentityBlacklist(XMLGregorianCalendar value) {
        this.periodIdentityBlacklist = value;
    }

    /**
     * Gets the value of the isGlobalWhitelist property.
     * 
     */
    public boolean isIsGlobalWhitelist() {
        return isGlobalWhitelist;
    }

    /**
     * Sets the value of the isGlobalWhitelist property.
     * 
     */
    public void setIsGlobalWhitelist(boolean value) {
        this.isGlobalWhitelist = value;
    }

    /**
     * Gets the value of the periodGlobalWhitelist property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPeriodGlobalWhitelist() {
        return periodGlobalWhitelist;
    }

    /**
     * Sets the value of the periodGlobalWhitelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPeriodGlobalWhitelist(XMLGregorianCalendar value) {
        this.periodGlobalWhitelist = value;
    }

    /**
     * Gets the value of the isMerchantWhitelist property.
     * 
     */
    public boolean isIsMerchantWhitelist() {
        return isMerchantWhitelist;
    }

    /**
     * Sets the value of the isMerchantWhitelist property.
     * 
     */
    public void setIsMerchantWhitelist(boolean value) {
        this.isMerchantWhitelist = value;
    }

    /**
     * Gets the value of the periodMerchantWhitelist property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPeriodMerchantWhitelist() {
        return periodMerchantWhitelist;
    }

    /**
     * Sets the value of the periodMerchantWhitelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPeriodMerchantWhitelist(XMLGregorianCalendar value) {
        this.periodMerchantWhitelist = value;
    }

    /**
     * Gets the value of the isIpFrequencyLimitReached property.
     * 
     */
    public boolean isIsIpFrequencyLimitReached() {
        return isIpFrequencyLimitReached;
    }

    /**
     * Sets the value of the isIpFrequencyLimitReached property.
     * 
     */
    public void setIsIpFrequencyLimitReached(boolean value) {
        this.isIpFrequencyLimitReached = value;
    }

    /**
     * Gets the value of the isInvalidEmail property.
     * 
     */
    public boolean isIsInvalidEmail() {
        return isInvalidEmail;
    }

    /**
     * Sets the value of the isInvalidEmail property.
     * 
     */
    public void setIsInvalidEmail(boolean value) {
        this.isInvalidEmail = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            boolean theIsAddressBlacklist;
            theIsAddressBlacklist = (true?this.isIsAddressBlacklist():false);
            strategy.appendField(locator, this, "isAddressBlacklist", buffer, theIsAddressBlacklist);
        }
        {
            XMLGregorianCalendar thePeriodAddressBlacklist;
            thePeriodAddressBlacklist = this.getPeriodAddressBlacklist();
            strategy.appendField(locator, this, "periodAddressBlacklist", buffer, thePeriodAddressBlacklist);
        }
        {
            boolean theIsEmailBlacklist;
            theIsEmailBlacklist = (true?this.isIsEmailBlacklist():false);
            strategy.appendField(locator, this, "isEmailBlacklist", buffer, theIsEmailBlacklist);
        }
        {
            XMLGregorianCalendar thePeriodEmailBlacklist;
            thePeriodEmailBlacklist = this.getPeriodEmailBlacklist();
            strategy.appendField(locator, this, "periodEmailBlacklist", buffer, thePeriodEmailBlacklist);
        }
        {
            boolean theIsFraudBlacklist;
            theIsFraudBlacklist = (true?this.isIsFraudBlacklist():false);
            strategy.appendField(locator, this, "isFraudBlacklist", buffer, theIsFraudBlacklist);
        }
        {
            XMLGregorianCalendar thePeriodFraudBlacklist;
            thePeriodFraudBlacklist = this.getPeriodFraudBlacklist();
            strategy.appendField(locator, this, "periodFraudBlacklist", buffer, thePeriodFraudBlacklist);
        }
        {
            boolean theIsIdentityBlacklist;
            theIsIdentityBlacklist = (true?this.isIsIdentityBlacklist():false);
            strategy.appendField(locator, this, "isIdentityBlacklist", buffer, theIsIdentityBlacklist);
        }
        {
            XMLGregorianCalendar thePeriodIdentityBlacklist;
            thePeriodIdentityBlacklist = this.getPeriodIdentityBlacklist();
            strategy.appendField(locator, this, "periodIdentityBlacklist", buffer, thePeriodIdentityBlacklist);
        }
        {
            boolean theIsGlobalWhitelist;
            theIsGlobalWhitelist = (true?this.isIsGlobalWhitelist():false);
            strategy.appendField(locator, this, "isGlobalWhitelist", buffer, theIsGlobalWhitelist);
        }
        {
            XMLGregorianCalendar thePeriodGlobalWhitelist;
            thePeriodGlobalWhitelist = this.getPeriodGlobalWhitelist();
            strategy.appendField(locator, this, "periodGlobalWhitelist", buffer, thePeriodGlobalWhitelist);
        }
        {
            boolean theIsMerchantWhitelist;
            theIsMerchantWhitelist = (true?this.isIsMerchantWhitelist():false);
            strategy.appendField(locator, this, "isMerchantWhitelist", buffer, theIsMerchantWhitelist);
        }
        {
            XMLGregorianCalendar thePeriodMerchantWhitelist;
            thePeriodMerchantWhitelist = this.getPeriodMerchantWhitelist();
            strategy.appendField(locator, this, "periodMerchantWhitelist", buffer, thePeriodMerchantWhitelist);
        }
        {
            boolean theIsIpFrequencyLimitReached;
            theIsIpFrequencyLimitReached = (true?this.isIsIpFrequencyLimitReached():false);
            strategy.appendField(locator, this, "isIpFrequencyLimitReached", buffer, theIsIpFrequencyLimitReached);
        }
        {
            boolean theIsInvalidEmail;
            theIsInvalidEmail = (true?this.isIsInvalidEmail():false);
            strategy.appendField(locator, this, "isInvalidEmail", buffer, theIsInvalidEmail);
        }
        return buffer;
    }

}
