//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.19 at 01:24:49 AM CEST 
//


package org.zmeu.blog.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for dataRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="company_details" type="{}CompanyDetailsType" minOccurs="0"/>
 *         &lt;element name="billing_address_data" type="{}BillingAddressDataType"/>
 *         &lt;element name="shipping_address_data" type="{}ShippingAddressDataType" minOccurs="0"/>
 *         &lt;element name="customer_attributes" type="{}CustomerAttributesType"/>
 *         &lt;element name="customer_bank_data" type="{}CustomerBankDataType" minOccurs="0"/>
 *         &lt;element name="customer_limit" type="{}CustomerLimitType"/>
 *         &lt;element name="rating_provider" type="{}RatingProviderType" maxOccurs="unbounded"/>
 *         &lt;element name="rating_provider_global_settings" type="{}RatingProviderGlobalSettingsType" maxOccurs="unbounded"/>
 *         &lt;element name="regis24_moma_box" type="{}Regis24MomaBoxType" minOccurs="0"/>
 *         &lt;element name="device_fingerprinting" type="{}DeviceFingerPrintingType" minOccurs="0"/>
 *         &lt;element name="blacklist_status" type="{}BlacklistStatusType"/>
 *         &lt;element name="order_details" type="{}OrderDetailsType"/>
 *         &lt;element name="technical_details" type="{}TechnicalDetailsType"/>
 *         &lt;element name="applicant_type" type="{}ApplicantTypeType"/>
 *         &lt;element name="workflow_name" type="{}WorkflowNameType"/>
 *         &lt;element name="merchant_details" type="{}MerchantDetailsType"/>
 *         &lt;element name="payment_history_within_last_three_months" type="{}OrderPaymentHistoryType"/>
 *         &lt;element name="payment_history_within_last_twelve_months" type="{}OrderPaymentHistoryType"/>
 *         &lt;element name="payment_history_since_ever" type="{}OrderPaymentHistoryType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataRequestType", propOrder = {
    "companyDetails",
    "billingAddressData",
    "shippingAddressData",
    "customerAttributes",
    "customerBankData",
    "customerLimit",
    "ratingProvider",
    "ratingProviderGlobalSettings",
    "regis24MomaBox",
    "deviceFingerprinting",
    "blacklistStatus",
    "orderDetails",
    "technicalDetails",
    "applicantType",
    "workflowName",
    "merchantDetails",
    "paymentHistoryWithinLastThreeMonths",
    "paymentHistoryWithinLastTwelveMonths",
    "paymentHistorySinceEver"
})
public class DataRequestType
    implements ToString
{

    @XmlElement(name = "company_details")
    protected CompanyDetailsType companyDetails;
    @XmlElement(name = "billing_address_data", required = true)
    protected BillingAddressDataType billingAddressData;
    @XmlElement(name = "shipping_address_data")
    protected ShippingAddressDataType shippingAddressData;
    @XmlElement(name = "customer_attributes", required = true)
    protected CustomerAttributesType customerAttributes;
    @XmlElement(name = "customer_bank_data")
    protected CustomerBankDataType customerBankData;
    @XmlElement(name = "customer_limit", required = true)
    protected CustomerLimitType customerLimit;
    @XmlElement(name = "rating_provider", required = true)
    protected List<RatingProviderType> ratingProvider;
    @XmlElement(name = "rating_provider_global_settings", required = true)
    protected List<RatingProviderGlobalSettingsType> ratingProviderGlobalSettings;
    @XmlElement(name = "regis24_moma_box")
    protected Regis24MomaBoxType regis24MomaBox;
    @XmlElement(name = "device_fingerprinting")
    protected DeviceFingerPrintingType deviceFingerprinting;
    @XmlElement(name = "blacklist_status", required = true)
    protected BlacklistStatusType blacklistStatus;
    @XmlElement(name = "order_details", required = true)
    protected OrderDetailsType orderDetails;
    @XmlElement(name = "technical_details", required = true)
    protected TechnicalDetailsType technicalDetails;
    @XmlElement(name = "applicant_type", required = true)
    protected ApplicantTypeType applicantType;
    @XmlElement(name = "workflow_name", required = true)
    protected WorkflowNameType workflowName;
    @XmlElement(name = "merchant_details", required = true)
    protected MerchantDetailsType merchantDetails;
    @XmlElement(name = "payment_history_within_last_three_months", required = true)
    protected OrderPaymentHistoryType paymentHistoryWithinLastThreeMonths;
    @XmlElement(name = "payment_history_within_last_twelve_months", required = true)
    protected OrderPaymentHistoryType paymentHistoryWithinLastTwelveMonths;
    @XmlElement(name = "payment_history_since_ever", required = true)
    protected OrderPaymentHistoryType paymentHistorySinceEver;

    /**
     * Gets the value of the companyDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyDetailsType }
     *     
     */
    public CompanyDetailsType getCompanyDetails() {
        return companyDetails;
    }

    /**
     * Sets the value of the companyDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyDetailsType }
     *     
     */
    public void setCompanyDetails(CompanyDetailsType value) {
        this.companyDetails = value;
    }

    /**
     * Gets the value of the billingAddressData property.
     * 
     * @return
     *     possible object is
     *     {@link BillingAddressDataType }
     *     
     */
    public BillingAddressDataType getBillingAddressData() {
        return billingAddressData;
    }

    /**
     * Sets the value of the billingAddressData property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillingAddressDataType }
     *     
     */
    public void setBillingAddressData(BillingAddressDataType value) {
        this.billingAddressData = value;
    }

    /**
     * Gets the value of the shippingAddressData property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingAddressDataType }
     *     
     */
    public ShippingAddressDataType getShippingAddressData() {
        return shippingAddressData;
    }

    /**
     * Sets the value of the shippingAddressData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingAddressDataType }
     *     
     */
    public void setShippingAddressData(ShippingAddressDataType value) {
        this.shippingAddressData = value;
    }

    /**
     * Gets the value of the customerAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerAttributesType }
     *     
     */
    public CustomerAttributesType getCustomerAttributes() {
        return customerAttributes;
    }

    /**
     * Sets the value of the customerAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerAttributesType }
     *     
     */
    public void setCustomerAttributes(CustomerAttributesType value) {
        this.customerAttributes = value;
    }

    /**
     * Gets the value of the customerBankData property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerBankDataType }
     *     
     */
    public CustomerBankDataType getCustomerBankData() {
        return customerBankData;
    }

    /**
     * Sets the value of the customerBankData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerBankDataType }
     *     
     */
    public void setCustomerBankData(CustomerBankDataType value) {
        this.customerBankData = value;
    }

    /**
     * Gets the value of the customerLimit property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerLimitType }
     *     
     */
    public CustomerLimitType getCustomerLimit() {
        return customerLimit;
    }

    /**
     * Sets the value of the customerLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerLimitType }
     *     
     */
    public void setCustomerLimit(CustomerLimitType value) {
        this.customerLimit = value;
    }

    /**
     * Gets the value of the ratingProvider property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ratingProvider property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRatingProvider().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RatingProviderType }
     * 
     * 
     */
    public List<RatingProviderType> getRatingProvider() {
        if (ratingProvider == null) {
            ratingProvider = new ArrayList<RatingProviderType>();
        }
        return this.ratingProvider;
    }

    /**
     * Gets the value of the ratingProviderGlobalSettings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ratingProviderGlobalSettings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRatingProviderGlobalSettings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RatingProviderGlobalSettingsType }
     * 
     * 
     */
    public List<RatingProviderGlobalSettingsType> getRatingProviderGlobalSettings() {
        if (ratingProviderGlobalSettings == null) {
            ratingProviderGlobalSettings = new ArrayList<RatingProviderGlobalSettingsType>();
        }
        return this.ratingProviderGlobalSettings;
    }

    /**
     * Gets the value of the regis24MomaBox property.
     * 
     * @return
     *     possible object is
     *     {@link Regis24MomaBoxType }
     *     
     */
    public Regis24MomaBoxType getRegis24MomaBox() {
        return regis24MomaBox;
    }

    /**
     * Sets the value of the regis24MomaBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link Regis24MomaBoxType }
     *     
     */
    public void setRegis24MomaBox(Regis24MomaBoxType value) {
        this.regis24MomaBox = value;
    }

    /**
     * Gets the value of the deviceFingerprinting property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceFingerPrintingType }
     *     
     */
    public DeviceFingerPrintingType getDeviceFingerprinting() {
        return deviceFingerprinting;
    }

    /**
     * Sets the value of the deviceFingerprinting property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceFingerPrintingType }
     *     
     */
    public void setDeviceFingerprinting(DeviceFingerPrintingType value) {
        this.deviceFingerprinting = value;
    }

    /**
     * Gets the value of the blacklistStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BlacklistStatusType }
     *     
     */
    public BlacklistStatusType getBlacklistStatus() {
        return blacklistStatus;
    }

    /**
     * Sets the value of the blacklistStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlacklistStatusType }
     *     
     */
    public void setBlacklistStatus(BlacklistStatusType value) {
        this.blacklistStatus = value;
    }

    /**
     * Gets the value of the orderDetails property.
     * 
     * @return
     *     possible object is
     *     {@link OrderDetailsType }
     *     
     */
    public OrderDetailsType getOrderDetails() {
        return orderDetails;
    }

    /**
     * Sets the value of the orderDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderDetailsType }
     *     
     */
    public void setOrderDetails(OrderDetailsType value) {
        this.orderDetails = value;
    }

    /**
     * Gets the value of the technicalDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicalDetailsType }
     *     
     */
    public TechnicalDetailsType getTechnicalDetails() {
        return technicalDetails;
    }

    /**
     * Sets the value of the technicalDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicalDetailsType }
     *     
     */
    public void setTechnicalDetails(TechnicalDetailsType value) {
        this.technicalDetails = value;
    }

    /**
     * Gets the value of the applicantType property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicantTypeType }
     *     
     */
    public ApplicantTypeType getApplicantType() {
        return applicantType;
    }

    /**
     * Sets the value of the applicantType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicantTypeType }
     *     
     */
    public void setApplicantType(ApplicantTypeType value) {
        this.applicantType = value;
    }

    /**
     * Gets the value of the workflowName property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowNameType }
     *     
     */
    public WorkflowNameType getWorkflowName() {
        return workflowName;
    }

    /**
     * Sets the value of the workflowName property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowNameType }
     *     
     */
    public void setWorkflowName(WorkflowNameType value) {
        this.workflowName = value;
    }

    /**
     * Gets the value of the merchantDetails property.
     * 
     * @return
     *     possible object is
     *     {@link MerchantDetailsType }
     *     
     */
    public MerchantDetailsType getMerchantDetails() {
        return merchantDetails;
    }

    /**
     * Sets the value of the merchantDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchantDetailsType }
     *     
     */
    public void setMerchantDetails(MerchantDetailsType value) {
        this.merchantDetails = value;
    }

    /**
     * Gets the value of the paymentHistoryWithinLastThreeMonths property.
     * 
     * @return
     *     possible object is
     *     {@link OrderPaymentHistoryType }
     *     
     */
    public OrderPaymentHistoryType getPaymentHistoryWithinLastThreeMonths() {
        return paymentHistoryWithinLastThreeMonths;
    }

    /**
     * Sets the value of the paymentHistoryWithinLastThreeMonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderPaymentHistoryType }
     *     
     */
    public void setPaymentHistoryWithinLastThreeMonths(OrderPaymentHistoryType value) {
        this.paymentHistoryWithinLastThreeMonths = value;
    }

    /**
     * Gets the value of the paymentHistoryWithinLastTwelveMonths property.
     * 
     * @return
     *     possible object is
     *     {@link OrderPaymentHistoryType }
     *     
     */
    public OrderPaymentHistoryType getPaymentHistoryWithinLastTwelveMonths() {
        return paymentHistoryWithinLastTwelveMonths;
    }

    /**
     * Sets the value of the paymentHistoryWithinLastTwelveMonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderPaymentHistoryType }
     *     
     */
    public void setPaymentHistoryWithinLastTwelveMonths(OrderPaymentHistoryType value) {
        this.paymentHistoryWithinLastTwelveMonths = value;
    }

    /**
     * Gets the value of the paymentHistorySinceEver property.
     * 
     * @return
     *     possible object is
     *     {@link OrderPaymentHistoryType }
     *     
     */
    public OrderPaymentHistoryType getPaymentHistorySinceEver() {
        return paymentHistorySinceEver;
    }

    /**
     * Sets the value of the paymentHistorySinceEver property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderPaymentHistoryType }
     *     
     */
    public void setPaymentHistorySinceEver(OrderPaymentHistoryType value) {
        this.paymentHistorySinceEver = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            CompanyDetailsType theCompanyDetails;
            theCompanyDetails = this.getCompanyDetails();
            strategy.appendField(locator, this, "companyDetails", buffer, theCompanyDetails);
        }
        {
            BillingAddressDataType theBillingAddressData;
            theBillingAddressData = this.getBillingAddressData();
            strategy.appendField(locator, this, "billingAddressData", buffer, theBillingAddressData);
        }
        {
            ShippingAddressDataType theShippingAddressData;
            theShippingAddressData = this.getShippingAddressData();
            strategy.appendField(locator, this, "shippingAddressData", buffer, theShippingAddressData);
        }
        {
            CustomerAttributesType theCustomerAttributes;
            theCustomerAttributes = this.getCustomerAttributes();
            strategy.appendField(locator, this, "customerAttributes", buffer, theCustomerAttributes);
        }
        {
            CustomerBankDataType theCustomerBankData;
            theCustomerBankData = this.getCustomerBankData();
            strategy.appendField(locator, this, "customerBankData", buffer, theCustomerBankData);
        }
        {
            CustomerLimitType theCustomerLimit;
            theCustomerLimit = this.getCustomerLimit();
            strategy.appendField(locator, this, "customerLimit", buffer, theCustomerLimit);
        }
        {
            List<RatingProviderType> theRatingProvider;
            theRatingProvider = (((this.ratingProvider!= null)&&(!this.ratingProvider.isEmpty()))?this.getRatingProvider():null);
            strategy.appendField(locator, this, "ratingProvider", buffer, theRatingProvider);
        }
        {
            List<RatingProviderGlobalSettingsType> theRatingProviderGlobalSettings;
            theRatingProviderGlobalSettings = (((this.ratingProviderGlobalSettings!= null)&&(!this.ratingProviderGlobalSettings.isEmpty()))?this.getRatingProviderGlobalSettings():null);
            strategy.appendField(locator, this, "ratingProviderGlobalSettings", buffer, theRatingProviderGlobalSettings);
        }
        {
            Regis24MomaBoxType theRegis24MomaBox;
            theRegis24MomaBox = this.getRegis24MomaBox();
            strategy.appendField(locator, this, "regis24MomaBox", buffer, theRegis24MomaBox);
        }
        {
            DeviceFingerPrintingType theDeviceFingerprinting;
            theDeviceFingerprinting = this.getDeviceFingerprinting();
            strategy.appendField(locator, this, "deviceFingerprinting", buffer, theDeviceFingerprinting);
        }
        {
            BlacklistStatusType theBlacklistStatus;
            theBlacklistStatus = this.getBlacklistStatus();
            strategy.appendField(locator, this, "blacklistStatus", buffer, theBlacklistStatus);
        }
        {
            OrderDetailsType theOrderDetails;
            theOrderDetails = this.getOrderDetails();
            strategy.appendField(locator, this, "orderDetails", buffer, theOrderDetails);
        }
        {
            TechnicalDetailsType theTechnicalDetails;
            theTechnicalDetails = this.getTechnicalDetails();
            strategy.appendField(locator, this, "technicalDetails", buffer, theTechnicalDetails);
        }
        {
            ApplicantTypeType theApplicantType;
            theApplicantType = this.getApplicantType();
            strategy.appendField(locator, this, "applicantType", buffer, theApplicantType);
        }
        {
            WorkflowNameType theWorkflowName;
            theWorkflowName = this.getWorkflowName();
            strategy.appendField(locator, this, "workflowName", buffer, theWorkflowName);
        }
        {
            MerchantDetailsType theMerchantDetails;
            theMerchantDetails = this.getMerchantDetails();
            strategy.appendField(locator, this, "merchantDetails", buffer, theMerchantDetails);
        }
        {
            OrderPaymentHistoryType thePaymentHistoryWithinLastThreeMonths;
            thePaymentHistoryWithinLastThreeMonths = this.getPaymentHistoryWithinLastThreeMonths();
            strategy.appendField(locator, this, "paymentHistoryWithinLastThreeMonths", buffer, thePaymentHistoryWithinLastThreeMonths);
        }
        {
            OrderPaymentHistoryType thePaymentHistoryWithinLastTwelveMonths;
            thePaymentHistoryWithinLastTwelveMonths = this.getPaymentHistoryWithinLastTwelveMonths();
            strategy.appendField(locator, this, "paymentHistoryWithinLastTwelveMonths", buffer, thePaymentHistoryWithinLastTwelveMonths);
        }
        {
            OrderPaymentHistoryType thePaymentHistorySinceEver;
            thePaymentHistorySinceEver = this.getPaymentHistorySinceEver();
            strategy.appendField(locator, this, "paymentHistorySinceEver", buffer, thePaymentHistorySinceEver);
        }
        return buffer;
    }

}
