//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.19 at 01:24:49 AM CEST 
//


package org.zmeu.blog.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.zmeu.blog.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DataRequest_QNAME = new QName("", "dataRequest");
    private final static QName _DataResponse_QNAME = new QName("", "dataResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.zmeu.blog.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataRequestType }
     * 
     */
    public DataRequestType createDataRequestType() {
        return new DataRequestType();
    }

    /**
     * Create an instance of {@link DataResponseType }
     * 
     */
    public DataResponseType createDataResponseType() {
        return new DataResponseType();
    }

    /**
     * Create an instance of {@link DeviceFingerPrintingType }
     * 
     */
    public DeviceFingerPrintingType createDeviceFingerPrintingType() {
        return new DeviceFingerPrintingType();
    }

    /**
     * Create an instance of {@link RatingProviderType }
     * 
     */
    public RatingProviderType createRatingProviderType() {
        return new RatingProviderType();
    }

    /**
     * Create an instance of {@link CustomerAttributesType }
     * 
     */
    public CustomerAttributesType createCustomerAttributesType() {
        return new CustomerAttributesType();
    }

    /**
     * Create an instance of {@link OrderPaymentHistoryType }
     * 
     */
    public OrderPaymentHistoryType createOrderPaymentHistoryType() {
        return new OrderPaymentHistoryType();
    }

    /**
     * Create an instance of {@link OrderHistoryType }
     * 
     */
    public OrderHistoryType createOrderHistoryType() {
        return new OrderHistoryType();
    }

    /**
     * Create an instance of {@link RatingProviderResultType }
     * 
     */
    public RatingProviderResultType createRatingProviderResultType() {
        return new RatingProviderResultType();
    }

    /**
     * Create an instance of {@link CancellationHistoryType }
     * 
     */
    public CancellationHistoryType createCancellationHistoryType() {
        return new CancellationHistoryType();
    }

    /**
     * Create an instance of {@link CompanyDetailsType }
     * 
     */
    public CompanyDetailsType createCompanyDetailsType() {
        return new CompanyDetailsType();
    }

    /**
     * Create an instance of {@link TechnicalDetailsType }
     * 
     */
    public TechnicalDetailsType createTechnicalDetailsType() {
        return new TechnicalDetailsType();
    }

    /**
     * Create an instance of {@link DebtsInDunningType }
     * 
     */
    public DebtsInDunningType createDebtsInDunningType() {
        return new DebtsInDunningType();
    }

    /**
     * Create an instance of {@link BlacklistUpdatesType }
     * 
     */
    public BlacklistUpdatesType createBlacklistUpdatesType() {
        return new BlacklistUpdatesType();
    }

    /**
     * Create an instance of {@link ErrorMessageType }
     * 
     */
    public ErrorMessageType createErrorMessageType() {
        return new ErrorMessageType();
    }

    /**
     * Create an instance of {@link BillingAddressDataType }
     * 
     */
    public BillingAddressDataType createBillingAddressDataType() {
        return new BillingAddressDataType();
    }

    /**
     * Create an instance of {@link PersonReturnedType }
     * 
     */
    public PersonReturnedType createPersonReturnedType() {
        return new PersonReturnedType();
    }

    /**
     * Create an instance of {@link PaymentHistoryType }
     * 
     */
    public PaymentHistoryType createPaymentHistoryType() {
        return new PaymentHistoryType();
    }

    /**
     * Create an instance of {@link Regis24MomaBoxType }
     * 
     */
    public Regis24MomaBoxType createRegis24MomaBoxType() {
        return new Regis24MomaBoxType();
    }

    /**
     * Create an instance of {@link ShippingAddressDataType }
     * 
     */
    public ShippingAddressDataType createShippingAddressDataType() {
        return new ShippingAddressDataType();
    }

    /**
     * Create an instance of {@link PaymentRegulationType }
     * 
     */
    public PaymentRegulationType createPaymentRegulationType() {
        return new PaymentRegulationType();
    }

    /**
     * Create an instance of {@link MerchantDetailsType }
     * 
     */
    public MerchantDetailsType createMerchantDetailsType() {
        return new MerchantDetailsType();
    }

    /**
     * Create an instance of {@link WorkflowNameType }
     * 
     */
    public WorkflowNameType createWorkflowNameType() {
        return new WorkflowNameType();
    }

    /**
     * Create an instance of {@link OrderDetailsType }
     * 
     */
    public OrderDetailsType createOrderDetailsType() {
        return new OrderDetailsType();
    }

    /**
     * Create an instance of {@link DataMessageType }
     * 
     */
    public DataMessageType createDataMessageType() {
        return new DataMessageType();
    }

    /**
     * Create an instance of {@link BlacklistStatusType }
     * 
     */
    public BlacklistStatusType createBlacklistStatusType() {
        return new BlacklistStatusType();
    }

    /**
     * Create an instance of {@link RatingProviderGlobalSettingsType }
     * 
     */
    public RatingProviderGlobalSettingsType createRatingProviderGlobalSettingsType() {
        return new RatingProviderGlobalSettingsType();
    }

    /**
     * Create an instance of {@link CustomerLimitType }
     * 
     */
    public CustomerLimitType createCustomerLimitType() {
        return new CustomerLimitType();
    }

    /**
     * Create an instance of {@link RatingResultType }
     * 
     */
    public RatingResultType createRatingResultType() {
        return new RatingResultType();
    }

    /**
     * Create an instance of {@link ApplicantTypeType }
     * 
     */
    public ApplicantTypeType createApplicantTypeType() {
        return new ApplicantTypeType();
    }

    /**
     * Create an instance of {@link CustomerBankDataType }
     * 
     */
    public CustomerBankDataType createCustomerBankDataType() {
        return new CustomerBankDataType();
    }

    /**
     * Create an instance of {@link OpenDebtsType }
     * 
     */
    public OpenDebtsType createOpenDebtsType() {
        return new OpenDebtsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dataRequest")
    public JAXBElement<DataRequestType> createDataRequest(DataRequestType value) {
        return new JAXBElement<DataRequestType>(_DataRequest_QNAME, DataRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dataResponse")
    public JAXBElement<DataResponseType> createDataResponse(DataResponseType value) {
        return new JAXBElement<DataResponseType>(_DataResponse_QNAME, DataResponseType.class, null, value);
    }

}
