//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.19 at 01:24:49 AM CEST 
//


package org.zmeu.blog.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for OrderHistoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderHistoryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="sum" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="day_of_week" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="order_amounts" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded"/>
 *         &lt;element name="portal_id" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded"/>
 *         &lt;element name="time_of_day" type="{http://www.w3.org/2001/XMLSchema}dateTime" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderHistoryType", propOrder = {
    "quantity",
    "sum",
    "dayOfWeek",
    "orderAmounts",
    "portalId",
    "timeOfDay"
})
public class OrderHistoryType
    implements ToString
{

    protected long quantity;
    protected long sum;
    @XmlElement(name = "day_of_week", required = true)
    protected List<String> dayOfWeek;
    @XmlElement(name = "order_amounts", type = Long.class)
    protected List<Long> orderAmounts;
    @XmlElement(name = "portal_id", type = Long.class)
    protected List<Long> portalId;
    @XmlElement(name = "time_of_day", required = true)
    @XmlSchemaType(name = "dateTime")
    protected List<XMLGregorianCalendar> timeOfDay;

    /**
     * Gets the value of the quantity property.
     * 
     */
    public long getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(long value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the sum property.
     * 
     */
    public long getSum() {
        return sum;
    }

    /**
     * Sets the value of the sum property.
     * 
     */
    public void setSum(long value) {
        this.sum = value;
    }

    /**
     * Gets the value of the dayOfWeek property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dayOfWeek property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDayOfWeek().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDayOfWeek() {
        if (dayOfWeek == null) {
            dayOfWeek = new ArrayList<String>();
        }
        return this.dayOfWeek;
    }

    /**
     * Gets the value of the orderAmounts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderAmounts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderAmounts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getOrderAmounts() {
        if (orderAmounts == null) {
            orderAmounts = new ArrayList<Long>();
        }
        return this.orderAmounts;
    }

    /**
     * Gets the value of the portalId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portalId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortalId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getPortalId() {
        if (portalId == null) {
            portalId = new ArrayList<Long>();
        }
        return this.portalId;
    }

    /**
     * Gets the value of the timeOfDay property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timeOfDay property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimeOfDay().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLGregorianCalendar }
     * 
     * 
     */
    public List<XMLGregorianCalendar> getTimeOfDay() {
        if (timeOfDay == null) {
            timeOfDay = new ArrayList<XMLGregorianCalendar>();
        }
        return this.timeOfDay;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            long theQuantity;
            theQuantity = (true?this.getQuantity(): 0L);
            strategy.appendField(locator, this, "quantity", buffer, theQuantity);
        }
        {
            long theSum;
            theSum = (true?this.getSum(): 0L);
            strategy.appendField(locator, this, "sum", buffer, theSum);
        }
        {
            List<String> theDayOfWeek;
            theDayOfWeek = (((this.dayOfWeek!= null)&&(!this.dayOfWeek.isEmpty()))?this.getDayOfWeek():null);
            strategy.appendField(locator, this, "dayOfWeek", buffer, theDayOfWeek);
        }
        {
            List<Long> theOrderAmounts;
            theOrderAmounts = (((this.orderAmounts!= null)&&(!this.orderAmounts.isEmpty()))?this.getOrderAmounts():null);
            strategy.appendField(locator, this, "orderAmounts", buffer, theOrderAmounts);
        }
        {
            List<Long> thePortalId;
            thePortalId = (((this.portalId!= null)&&(!this.portalId.isEmpty()))?this.getPortalId():null);
            strategy.appendField(locator, this, "portalId", buffer, thePortalId);
        }
        {
            List<XMLGregorianCalendar> theTimeOfDay;
            theTimeOfDay = (((this.timeOfDay!= null)&&(!this.timeOfDay.isEmpty()))?this.getTimeOfDay():null);
            strategy.appendField(locator, this, "timeOfDay", buffer, theTimeOfDay);
        }
        return buffer;
    }

}
