//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.19 at 01:24:49 AM CEST 
//


package org.zmeu.blog.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for RatingProviderGlobalSettingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RatingProviderGlobalSettingsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rating_provider_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="rating_provider_enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RatingProviderGlobalSettingsType", propOrder = {
    "ratingProviderId",
    "ratingProviderEnabled"
})
public class RatingProviderGlobalSettingsType
    implements ToString
{

    @XmlElement(name = "rating_provider_id")
    protected long ratingProviderId;
    @XmlElement(name = "rating_provider_enabled")
    protected boolean ratingProviderEnabled;

    /**
     * Gets the value of the ratingProviderId property.
     * 
     */
    public long getRatingProviderId() {
        return ratingProviderId;
    }

    /**
     * Sets the value of the ratingProviderId property.
     * 
     */
    public void setRatingProviderId(long value) {
        this.ratingProviderId = value;
    }

    /**
     * Gets the value of the ratingProviderEnabled property.
     * 
     */
    public boolean isRatingProviderEnabled() {
        return ratingProviderEnabled;
    }

    /**
     * Sets the value of the ratingProviderEnabled property.
     * 
     */
    public void setRatingProviderEnabled(boolean value) {
        this.ratingProviderEnabled = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            long theRatingProviderId;
            theRatingProviderId = (true?this.getRatingProviderId(): 0L);
            strategy.appendField(locator, this, "ratingProviderId", buffer, theRatingProviderId);
        }
        {
            boolean theRatingProviderEnabled;
            theRatingProviderEnabled = (true?this.isRatingProviderEnabled():false);
            strategy.appendField(locator, this, "ratingProviderEnabled", buffer, theRatingProviderEnabled);
        }
        return buffer;
    }

}
